import React from 'react';
import './About.css';
import heroImage from '../../assets/images/hero-about.jpg';
import aatheImage from '../../assets/images/aathe.jpg';
import aasikhaImage from '../../assets/images/aasikha.jpg';
import ananyaImage from '../../assets/images/ananya.jpg';

const About = () => {
  const coreValues = [
    { icon: '🌱', title: 'Sustainability', description: 'Committed to environmental preservation through innovative waste management' },
    { icon: '💡', title: 'Innovation', description: 'Leveraging technology to transform waste management practices' },
    { icon: '🤝', title: 'Community', description: 'Building partnerships for a cleaner, greener future' },
    { icon: '♻️', title: 'Circular Economy', description: 'Converting waste into valuable resources' }
  ];

  const impactMetrics = [
    { metric: '5+', label: 'Function Halls Served' },
    { metric: '50+', label: 'kgs Waste Diverted' },
    { metric: '20+', label: 'kgs Compost Produced' },
    { metric: '80%', label: 'Waste Recovery Rate' }
  ];

  const teamMembers = [
    {
      name: 'Aatheka Abdul',
      role: 'CEO & Co-founder',
      image: aatheImage,
      bio: 'Pursuing a degree in Computer Science and Engneering and passionate about developing tech based solutions.'
    },
    {
      name: 'Aasikha A',
      role: 'CFO & Co-founder',
      image: aasikhaImage,
      bio: 'Pursuing a degree in Computer Science and Engneering with a keen intrest on environmental sustainability.'
    },
    {
      name: 'Ananya',
      role: 'CMO & Co-founder',
      image: ananyaImage,
      bio: 'Pursuing a degree in Computer Science and Engneering and highly interested in designing and marketing.'
    }
  ];

  return (
    <div className="about-page">
      {/* Hero Section */}
      <section className="hero-section" style={{ backgroundImage: `linear-gradient(rgba(27, 94, 32, 0.8), rgba(27, 94, 32, 0.8)), url(${heroImage})`, backgroundColor: '#1B5E20' }}>
        <div className="hero-content">
          <h1>About EcoCrush: Revolutionizing Function Hall Waste Management</h1>
          <p>Transforming the way function halls manage waste through innovative technology and sustainable practices.</p>
        </div>
      </section>

      {/* Our Story Section */}
      <section className="story-section">
        <h2>Our Story</h2>
        <div className="timeline">
          <div className="timeline-item">
            <div className="timeline-content">
              <h3>The Beginning</h3>
              <p>Founded in 2025 by Aatheka, Ananya and Aasikha, who witnessed the massive waste generated by function halls.</p>
            </div>
          </div>
          <div className="timeline-item">
            <div className="timeline-content">
              <h3>Platform Launch</h3>
              <p>Developed and launched our innovative waste management platform connecting function halls with composters.</p>
            </div>
          </div>
          <div className="timeline-item">
            <div className="timeline-content">
              <h3>Growing Impact</h3>
              <p>Slowly expanding to serve function halls and establishing partnerships with leading composting facilities.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Mission & Vision Section */}
      <section className="mission-vision-section">
        <div className="mission">
          <h2>Our Mission</h2>
          <p>To revolutionize function hall waste management by creating a sustainable ecosystem that converts waste into valuable resources.</p>
        </div>
        <div className="vision">
          <h2>Our Vision</h2>
          <p>A world where all function hall waste is transformed into resources, creating a circular economy that benefits both businesses and the environment.</p>
        </div>
        <div className="core-values">
          <h2>Core Values</h2>
          <div className="values-grid">
            {coreValues.map((value, index) => (
              <div key={index} className="value-card">
                <span className="value-icon">{value.icon}</span>
                <h3>{value.title}</h3>
                <p>{value.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Our Approach Section */}
      <section className="approach-section">
        <h2>Our Approach</h2>
        <div className="process-steps">
          <div className="step">
            <span className="step-number">1</span>
            <h3>Collection</h3>
            <p>Scheduled waste pickup from function halls using our smart logistics system</p>
          </div>
          <div className="step">
            <span className="step-number">2</span>
            <h3>Sorting</h3>
            <p>Advanced waste segregation for maximum resource recovery</p>
          </div>
          <div className="step">
            <span className="step-number">3</span>
            <h3>Processing</h3>
            <p>Converting organic waste into high-quality compost</p>
          </div>
          <div className="step">
            <span className="step-number">4</span>
            <h3>Distribution</h3>
            <p>Delivering valuable resources to agricultural partners</p>
          </div>
        </div>
      </section>

      {/* Team Section */}
      <section className="team-section">
        <h2>Meet Our Team</h2>
        <div className="team-grid">
          {teamMembers.map((member, index) => (
            <div key={index} className="team-member">
              <div className="member-image"><img src={member.image} alt={member.name}></img></div>
              <h3>{member.name}</h3>
              <p className="member-role">{member.role}</p>
              <p className="member-bio">{member.bio}</p>
            </div>
          ))}
        </div>
        <div className="team-quote">
          <blockquote>
            "Our mission is to create a sustainable future by transforming waste management in the function hall industry."
            <footer>- Aatheka, CEO</footer>
          </blockquote>
        </div>
      </section>

      {/* Impact Metrics Section */}
      <section className="impact-section">
        <h2>Our Impact</h2>
        <div className="metrics-grid">
          {impactMetrics.map((item, index) => (
            <div key={index} className="metric-card">
              <h3>{item.metric}</h3>
              <p>{item.label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Call to Action Section */}
      <section className="cta-section">
        <h2>Join the Revolution</h2>
        <p>Be part of the sustainable waste management movement</p>
        <div className="cta-buttons">
          <a href="/auth" className="cta-button primary">Register Now</a>
          <a href="/contact" className="cta-button secondary">Contact Us</a>
        </div>
      </section>
    </div>
  );
};

export default About;
